version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8083:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - $PWD/jenkins/jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net: