server:
  port: 8081

github:
  gh-credentials: "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"

aws-credentials:
  aws-public-key: "AKIAZOW6FHBCJVU3OA7O"
  aws-private-key: "iy/pruCQO/bxsGsFIUYsPSWacDqsMlKVziXufCKO"