server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://3.94.187.190:5432/test
    username: postgres
    password: 123987

aws-credentials:
  aws-public-key: ${AWS_CREDENTIALS_PUBLIC_KEY}
  aws-private-key: ${AWS_CREDENTIALS_PRIVATE_KEY}

github:
  gh-credentials: ${GITHUB_TOKEN}

jenkins:
  credentials: ${JENKINS_TOKEN}
